branches:
  only:
    - gh-pages
    - master
    - /.*/

language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests/
# if: branch = gh-pages
# deploy:
#   - provider: script
#     script: bash scripts/convert-model.sh
#     on:
#       branch: gh-pages
#   - provider: pages
#     skip_cleanup: true
#     keep_history: true
#     on:
#       branch: gh-pages
