dist: xenial

branches:
  only:
    - gh-pages
    - master
    - /.*/

language: python
python:
  - "3.6"

jobs:
  include:
    - name: test
      language: python
      python:
        - "3.6"
      install:
        - pip install -r requirements.txt
      cache:
        pip: true
      script:
        - pytest tests/
      # Conditional deployment
    - name: deployment
      if: branch = gh-pages
      deploy:
        - provider: script
          script: ./scripts/convert-model.sh
          on:
            branch: gh-pages
        # - provider: pages
        #   skip_cleanup: true
        #   keep_history: true
        #   on:
        #     branch: gh-pages
