branches:
  only:
    - gh-pages
    - master
    - /.*/

os:
  - linux
dist: xenial

language: python
python:
  - "3.6"

jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt
      script:
        - pytest tests/
      # Conditional deployment
      if: branch = gh-pages
      deploy:
        - provider: script
          script: echo "Deployment starting..."
          # script: bash scripts/convert-model.sh
          on:
            branch: gh-pages
        # - provider: pages
        #   skip_cleanup: true
        #   keep_history: true
        #   on:
        #     branch: gh-pages
# command to install dependencies
# install:
#   - pip install -r requirements.txt
# command to run tests
# script:
#   - pytest tests/
# if: branch = gh-pages
# deploy:
#   - provider: script
#     script: bash scripts/convert-model.sh
#     on:
#       branch: gh-pages
#   - provider: pages
#     skip_cleanup: true
#     keep_history: true
#     on:
#       branch: gh-pages
